// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXPgVlqPzrTS1trV9OkA62xw04kxV-X44',
    appId: '1:367125848541:web:c58ffd891c0ec9225b5634',
    messagingSenderId: '367125848541',
    projectId: 'up-orgs',
    authDomain: 'up-orgs.firebaseapp.com',
    storageBucket: 'up-orgs.appspot.com',
    measurementId: 'G-T93EV8P2RF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5hmYYe60FVj_ql5aB_F6zZwTtjDrgx8M',
    appId: '1:367125848541:android:945aec1255aa05d55b5634',
    messagingSenderId: '367125848541',
    projectId: 'up-orgs',
    storageBucket: 'up-orgs.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh3XecUWwpKervUvh6w3o5RYBebPQR2Oc',
    appId: '1:367125848541:ios:f79c8c9dac2e0baa5b5634',
    messagingSenderId: '367125848541',
    projectId: 'up-orgs',
    storageBucket: 'up-orgs.appspot.com',
    iosClientId: '367125848541-utn2ks2ia0iocmsk88fgn9a38eh1ppi2.apps.googleusercontent.com',
    iosBundleId: 'com.nesvier.upcapp.upOrgs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCh3XecUWwpKervUvh6w3o5RYBebPQR2Oc',
    appId: '1:367125848541:ios:f79c8c9dac2e0baa5b5634',
    messagingSenderId: '367125848541',
    projectId: 'up-orgs',
    storageBucket: 'up-orgs.appspot.com',
    iosClientId: '367125848541-utn2ks2ia0iocmsk88fgn9a38eh1ppi2.apps.googleusercontent.com',
    iosBundleId: 'com.nesvier.upcapp.upOrgs',
  );
}
